# Generated by Django 5.0.4 on 2024-05-02 02:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.UUID('98c600ca-8718-432a-992e-a305076848f0'), max_length=200, unique=True)),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
