# Generated by Django 5.0.4 on 2024-05-02 02:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(default=uuid.UUID('0acd9bc3-7ec2-4ec3-a78c-e6970080dfdb'), max_length=200, unique=True),
        ),
    ]
