# Generated by Django 5.0.4 on 2024-05-02 05:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(default=uuid.UUID('ebf3c56a-78b0-40f5-afb4-939a3fa43c0e'), max_length=200, unique=True),
        ),
    ]
